Repository netboxlabs/diode-agent, pull requests merged in 2024-07, with the labels that each got.

#3 feat: use installed community drivers on discovery
  diode-napalm-agent/diode_napalm/cli/cli.py
  diode-napalm-agent/diode_napalm/client.py
  diode-napalm-agent/diode_napalm/discovery.py
  diode-napalm-agent/diode_napalm/parser.py
  diode-napalm-agent/diode_napalm/translate.py
  diode-napalm-agent/tests/test_cli.py
  diode-napalm-agent/tests/test_discovery.py
Labels: python

#5 feat: diode-napalm-agent - add sample config and .env files
  diode-napalm-agent/README.md
  diode-napalm-agent/config.sample.yaml
  diode-napalm-agent/sample.env
Labels: markdown

#6 Update README.md
  diode-napalm-agent/README.md
Labels: markdown

#11 fix: remove vlan and hardcoded interface type
  diode-napalm-agent/README.md
  diode-napalm-agent/diode_napalm/cli/cli.py
  diode-napalm-agent/diode_napalm/client.py
  diode-napalm-agent/diode_napalm/translate.py
Labels: markdown, python
